console.log('Eiji Kumamoto')
console.log('---')
console.log("Eiji Kumamoto")
console.log('---')
console.log(`Eiji Kumamoto`)
console.log('---')
console.log("Eiji 'Kumamoto'")
console.log('---')
console.log('Eiji "Kumamoto"')
console.log('---')
console.log(`'Eiji' "Kumamoto"`)
console.log('---')